# Generated by Django 4.1.1 on 2022-10-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YWS1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
