# Generated by Django 4.1.1 on 2022-10-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YWS1', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_gmail', models.CharField(max_length=64)),
                ('user_order', models.CharField(max_length=64)),
            ],
        ),
    ]
