# Generated by Django 4.1.1 on 2022-11-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('gmail', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('authorised', models.BooleanField()),
            ],
        ),
    ]
