# Generated by Django 4.1.1 on 2022-11-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YWS2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='gmail',
            new_name='email',
        ),
    ]
