# Generated by Django 4.1.1 on 2022-10-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YWS1', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_order_date_day',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_order_date_hour',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_order_date_month',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
